{
 "title": "Live Machine Stats",
 "time": { "from": "now-2y", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Vibration Per Machine",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot-data\")\n  |> range(start: -2y)\n  |> filter(fn: (r) =>\n    r._measurement == \"iot_metrics\" and\n    r._field == \"Vibration_mm_s\"\n  )\n  |> group(columns: [\"Machine_ID\"])\n  |> last()\n  |> keep(columns: [\"_value\", \"Machine_ID\"])"
    }
   ]
  },
  {
   "title": "Tempratures Of Machines",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot-data\")\n  |> range(start: -2y)\n  |> filter(fn: (r) =>\n    r._measurement == \"iot_metrics\" and\n    r._field == \"Temperature_C\"\n  )\n  |> group(columns: [\"Machine_ID\"])\n  |> last()\n  |> keep(columns: [\"_value\", \"Machine_ID\"])\n"
    }
   ]
  },
  {
   "title": "Pressure Per Machine",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot-data\")\n  |> range(start: -2y)\n  |> filter(fn: (r) =>\n    r._measurement == \"iot_metrics\" and\n    r._field == \"Pressure_bar\"\n  )\n  |> group(columns: [\"Machine_ID\"])\n  |> last()\n  |> keep(columns: [\"_value\", \"Machine_ID\"])"
    }
   ]
  }
 ]
}