{
 "title": "Factory Analytics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "mv_machine_efficiency_monthly Overall",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT Month, SUM(Total_Power_kW) FROM mv_machine_efficiency_monthly GROUP BY Month ORDER BY Total_Power_kW DESC LIMIT 10;\n\n"
    }
   ]
  },
  {
   "title": "mv_machine_efficiency_monthly Latest",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT Machine_ID, SUM(Total_Power_kW) FROM mv_machine_efficiency_monthly GROUP BY Machine_ID ORDER BY Total_Power_kW DESC LIMIT 10"
    }
   ]
  },
  {
   "title": "mv_machine_efficiency_weekly Overall",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT ISO_Week, SUM(Total_Power_kW) FROM mv_machine_efficiency_weekly GROUP BY ISO_Week ORDER BY Total_Power_kW DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "mv_machine_efficiency_weekly Latest",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT Machine_ID, SUM(Total_Power_kW) FROM mv_machine_efficiency_weekly GROUP BY Machine_ID ORDER BY Total_Power_kW DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "mv_machine_efficiency_daily  Overall",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT Day, SUM(Total_Power_kW) FROM mv_machine_efficiency_daily GROUP BY Day ORDER BY Total_Power_kW DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "mv_machine_efficiency_daily Latest",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT Machine_ID, SUM(Total_Power_kW) FROM mv_machine_efficiency_daily GROUP BY Machine_ID ORDER BY Total_Power_kW DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "mv_machine_failures_monthly Overall",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT Month, SUM(Total_Power_kW) FROM mv_machine_failures_monthly GROUP BY Month ORDER BY Total_Power_kW DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "mv_machine_failures_monthly Latest",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT Machine_ID, SUM(Total_Power_kW) FROM mv_machine_failures_monthly GROUP BY Machine_ID ORDER BY Total_Power_kW DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "mv_machine_failures_weekly Overall",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT ISO_Week, SUM(Total_Power_kW) FROM mv_machine_failures_weekly GROUP BY ISO_Week ORDER BY Total_Power_kW DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "mv_machine_failures_weekly Latest",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT Machine_ID, SUM(Total_Power_kW) FROM mv_machine_failures_weekly GROUP BY Machine_ID ORDER BY Total_Power_kW DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "mv_machine_failures_daily Overall",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT Day, SUM(Total_Power_kW) FROM mv_machine_failures_daily GROUP BY Day ORDER BY Total_Power_kW DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "mv_machine_failures_daily Latest",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT Machine_ID, SUM(Total_Power_kW) FROM mv_machine_failures_daily GROUP BY Machine_ID ORDER BY Total_Power_kW DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "mv_unit_production_monthly Overalll",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "rawSql": "SELECT Month, SUM(Total_Power_kW) FROM mv_unit_production_monthly GROUP BY Month ORDER BY Total_Power_kW DESC LIMIT 10;\n\n"
    }
   ]
  },
  {
   "title": "mv_unit_production_monthly Latest",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "rawSql": "SELECT Machine_ID, SUM(Total_Power_kW) FROM mv_unit_production_monthly GROUP BY Machine_ID ORDER BY Total_Power_kW DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "mv_unit_production_weekly Overall ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "rawSql": "SELECT ISO_Week, SUM(Total_Power_kW) FROM mv_unit_production_weekly GROUP BY ISO_Week ORDER BY Total_Power_kW DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "mv_unit_production_weekly Latest ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "rawSql": "SELECT Machine_ID, SUM(Total_Power_kW) FROM mv_unit_production_weekly GROUP BY Machine_ID ORDER BY Total_Power_kW DESC LIMIT 10; "
    }
   ]
  },
  {
   "title": "mv_unit_production_daily Overall",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "rawSql": "SELECT Day, SUM(Total_Power_kW) FROM mv_unit_production_daily GROUP BY Day ORDER BY Total_Power_kW DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "mv_unit_production_daily Latest",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "rawSql": "SELECT Machine_ID, SUM(Total_Power_kW) FROM mv_unit_production_daily GROUP BY Machine_ID ORDER BY Total_Power_kW DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "mv_power_consumption_weekly Latest",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "rawSql": "SELECT Machine_ID,SUM(Total_Power_kW) from mv_power_consumption_weekly GROUP BY Machine_ID ORDER BY Total_Power_kW DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "mv_power_consumption_weekly Overall ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "rawSql": "SELECT ISO_Week,SUM(Total_Power_kW) from mv_power_consumption_weekly GROUP BY ISO_Week ORDER BY Total_Power_kW DESC;"
    }
   ]
  },
  {
   "title": "mv_power_consumption_monthly Latest",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "rawSql": "SELECT Machine_ID,Total_Power_kW from mv_power_consumption_monthly GROUP BY Machine_ID ORDER BY Total_Power_kW DESC; "
    }
   ]
  },
  {
   "title": "mv_power_consumption_monthly",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "rawSql": "SELECT Machine_ID,SUM(Total_Power_kW) from mv_power_consumption_monthly GROUP BY Machine_ID ORDER BY Month DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "mv_power_consumption_total_daily",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "rawSql": "SELECT Day,SUM(Total_Power_kW) FROM mv_power_consumption_total_daily GROUP BY Day ORDER BY Day desc LIMIT 10;\n"
    }
   ]
  },
  {
   "title": "mv_total_power_consumption_weekly",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "rawSql": "SELECT ISO_Week, SUM(Total_Power_kW) from mv_total_power_consumption_weekly GROUP BY ISO_Week ORDER BY ISO_Week DESC;"
    }
   ]
  },
  {
   "title": "Monthly Total Power Consumption Monthly",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "targets": [
    {
     "rawSql": "SELECT Month,Total_Power_kW from mv_total_power_consumption_monthly GROUP BY Month Order BY Month DESC;"
    }
   ]
  }
 ]
}