version: "3.8"
services:
  telegraf:
    image: telegraf
    container_name: telegraf
    networks:
      - kafka-nifi-net
    command: [ "telegraf", "--debug", "--config", "/etc/telegraf/telegraf.conf" ]
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf

  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - "8086:8086"
      - "8089:8089"
    env_file:
      - ./influx/influx.env

    networks:
      - kafka-nifi-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - kafka-nifi-net
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:

networks:
  kafka-nifi-net:
    external: true
    name: industrial-data-pipeline_kafka-nifi-net

