version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-nifi-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: always
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    volumes:
      - kafka_data:/var/lib/kafka/data
    depends_on:
      - zookeeper
    networks:
      - kafka-nifi-net

  nifi:
    image: apache/nifi:latest
    container_name: devnifi
    ports:
      - "8443:8443"
    environment:
      NIFI_WEB_HTTPS_PORT: '8443'
    volumes:
      - nifi_data:/opt/nifi/nifi-current
    restart: unless-stopped
    networks:
      - kafka-nifi-net

  nifi-registry:
    image: apache/nifi-registry:latest
    container_name: nifi-registry
    ports:
      - "18080:18080"
    volumes:
      - registry_data:/opt/nifi-registry/nifi-registry-current
    restart: unless-stopped
    networks:
      - kafka-nifi-net
      
  # MinIO Object Storage service
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
      - kafka-nifi-net
      
  # MinIO Client (mc) for bucket setup
  mc:
    image: minio/mc:latest
    container_name: mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/raw-data;
      /usr/bin/mc mb myminio/processed-data;
      /usr/bin/mc policy set public myminio/raw-data;
      /usr/bin/mc policy set public myminio/processed-data;
      exit 0;
      "
    networks:
      - kafka-nifi-net

volumes:
  kafka_data:
  nifi_data:
  registry_data:
  minio_data:

networks:
  kafka-nifi-net:
    external: true
    name: industrial-data-pipeline_kafka-nifi-net