version: '3.8'

services:
  # StarRocks all-in-one service
  starrocks:
    image: starrocks/allin1-ubuntu:3.4.1
    container_name: starrocks-allin1
    restart: unless-stopped
    ports:
      - "8030:8030" # FE HTTP port
      - "9020:9020" # FE RPC port
      - "9030:9030" # FE MySQL port
      - "8040:8040" # BE HTTP port
      - "9050:9050" # BE HeartBeat port
    volumes:
      - ./starrocks/fe/meta:/data/deploy/starrocks/fe/meta
      - ./starrocks/be/storage:/data/deploy/starrocks/be/storage
      - ./jars/mysql-connector-j-8.0.33.jar:/data/deploy/starrocks/fe/lib/mysql-connector-j-8.0.33.jar
    environment:
      - FE_CONF=enable_external_catalog=true;persistent_index.enable=true
      - BE_CONF=tablet_max_versions=10000;exec_mem_limit=2GB
    networks:
      - kafka-nifi-net

  # Spark Master service
  spark-master:
    image: bitnami/spark:3.3.2
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_EXTRA_CLASSPATH=/extra-jars
    ports:
      - "8090:8080"
      - "7077:7077"
    volumes:
      - ./data:/data
      - ./scripts:/scripts
      - ./jars:/extra-jars
    networks:
      - kafka-nifi-net

  # Spark Worker service
  spark-worker:
    image: bitnami/spark:3.3.2
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_HOST=0.0.0.0
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_EXTRA_CLASSPATH=/extra-jars
    volumes:
      - ./data:/data
      - ./scripts:/scripts
      - ./jars:/extra-jars
    networks:
      - kafka-nifi-net
    ports:
      - "8081:8081"

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: industrial_data
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - kafka-nifi-net

  jupyter:
    image: jupyter/pyspark-notebook:spark-3.3.2
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./jars:/home/jovyan/jars
    environment:
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=jupyter
      - PYSPARK_DRIVER_PYTHON_OPTS="notebook --NotebookApp.token='' --ip='*' --no-browser"
    networks:
      - kafka-nifi-net

volumes:
  starrocks_data:
  mysql_data:

networks:
  kafka-nifi-net:
    external: true
    name: industrial-data-pipeline_kafka-nifi-net 